import wasmModule from '@myriaddreamin/typst-ts-web-compiler/pkg/typst_ts_web_compiler_bg.wasm';

import { createTypstCompiler } from '@myriaddreamin/typst.ts';
import { CompileFormatEnum, type TypstCompiler } from '@myriaddreamin/typst.ts/compiler';

/** Bundled wasm has no embedded fonts; preload bytes so PDF text renders in Workers. */
const LIBERTINUS_REGULAR =
  'https://cdn.jsdelivr.net/gh/typst/typst-assets@v0.13.1/files/fonts/LibertinusSerif-Regular.otf';
const LIBERTINUS_BOLD =
  'https://cdn.jsdelivr.net/gh/typst/typst-assets@v0.13.1/files/fonts/LibertinusSerif-Bold.otf';

async function fetchFontBytes(url: string): Promise<Uint8Array> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Font fetch failed (${res.status}): ${url}`);
  }
  return new Uint8Array(await res.arrayBuffer());
}

const fixtureCatalog = [
  'fixtures/long-clip-arrow.typ',
  'fixtures/gradient-text-perf.typ',
];

const SAMPLE_TYP = `#set page(width: 210mm, height: 297mm)
#set text(font: "Libertinus Serif", size: 12pt)
= Hello from Cloudflare Worker
This PDF was generated by typst.ts.
`;

let compilerPromise: Promise<TypstCompiler> | null = null;

async function getCompiler(): Promise<TypstCompiler> {
  if (!compilerPromise) {
    compilerPromise = (async () => {
      const [regular, bold] = await Promise.all([
        fetchFontBytes(LIBERTINUS_REGULAR),
        fetchFontBytes(LIBERTINUS_BOLD),
      ]);

      const workerSafeFontLoader = Object.assign(
        async (_: unknown, { builder }: { builder: { add_raw_font(data: Uint8Array): Promise<void> } }) => {
          await builder.add_raw_font(regular);
          await builder.add_raw_font(bold);
        },
        {
          _kind: 'fontLoader',
          _preloadRemoteFontOptions: { assets: false },
        },
      );

      const compiler = createTypstCompiler();
      await compiler.init({
        getModule: () => wasmModule,
        // Avoid loadFonts(): it uses dynamic codegen (new Function), blocked in Workers.
        beforeBuild: [workerSafeFontLoader as any],
      });
      compiler.addSource('/main.typ', SAMPLE_TYP);
      return compiler;
    })();
  }
  return compilerPromise;
}

let probePromise: Promise<Record<string, unknown>> | null = null;

async function probeTypstPackages(): Promise<Record<string, unknown>> {
  if (!probePromise) {
    probePromise = (async () => {
      const compiler = await import('@myriaddreamin/typst-ts-web-compiler');
      const renderer = await import('@myriaddreamin/typst-ts-renderer');
      return {
        compilerExportCount: Object.keys(compiler).length,
        rendererExportCount: Object.keys(renderer).length,
        hasCompilerDefaultInit: typeof compiler.default === 'function',
        hasRendererDefaultInit: typeof renderer.default === 'function',
      };
    })();
  }
  return probePromise;
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8' },
  });
}

export default {
  async fetch(request: Request, _env: Env, _ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === '/') {
      return json({
        service: 'typst-cf-worker',
        message: 'Cloudflare Worker is up.',
        hint: 'GET /pdf for a sample PDF. GET /probe to verify wasm npm packages import.',
      });
    }

    if (url.pathname === '/probe') {
      try {
        const probe = await probeTypstPackages();
        return json({
          ok: true,
          packages: ['@myriaddreamin/typst-ts-web-compiler', '@myriaddreamin/typst-ts-renderer'],
          probe,
          fixtureCatalog,
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return json({ ok: false, error: message, fixtureCatalog }, 500);
      }
    }

    if (url.pathname === '/pdf') {
      try {
        const compiler = await getCompiler();
        const out = await compiler.compile({
          mainFilePath: '/main.typ',
          format: CompileFormatEnum.pdf,
          diagnostics: 'full',
        });

        if (!out.result) {
          return json(
            {
              ok: false,
              error: 'Compilation produced no PDF',
              diagnostics: out.diagnostics ?? [],
            },
            500,
          );
        }

        return new Response(out.result, {
          status: 200,
          headers: {
            'content-type': 'application/pdf',
            'content-disposition': 'inline; filename="sample.pdf"',
            'cache-control': 'no-store',
          },
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return json({ ok: false, error: message }, 500);
      }
    }

    return new Response('Not Found', { status: 404 });
  },
} satisfies ExportedHandler<Env>;
